name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - name: Bazel Setup
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v5
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: "Test"
        run: bazel test //...